version: "3.5"
services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest     #jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    group_add:
      - 103   # /etc/group 查看 render:x:122           
    network_mode: "host"
    volumes:
      - /root/jellyfin/config:/config
      - /root/jellyfin/cache:/cache
      - /home/gd:/media
    restart: "unless-stopped"
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    # Optional - alternative address used for autodiscovery
    #environment:
     # - JELLYFIN_PublishedServerUrl=http://example.com
