version: "3.5"
services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest     #jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:100
    network_mode: "host"
    volumes:
      - /root/jellyfin/config:/config
      - /root/jellyfin/cache:/cache
      - /home/gd:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    #environment:
     # - JELLYFIN_PublishedServerUrl=http://example.com
